#+title: Array
#+OPTIONS: todo:nil
#+LATEX_LISTINGS: t
#+LATEX_HEADER: \usepackage{minted}
Un array in java rappresenta un gruppo di variabili (chiamate elementi) tutte dello stesso tipo.

Gli array sono oggetti quindi le variabili di tipo array contengono il riferimento all'array in memoria. Gli elementi di un array possono essere tipi primitivi o riferimenti a oggetti.

Dichiarazione di un array senza valori. Ogni elemento è inzializzato con il valore di default.

#+begin_src java
int[] a; // dichiarazione
a = new int[10] // creazione senza valori

#+end_src

Creazione con valori
#+begin_src java
a = new int[] {-5, -2, 3, 0, 1, -6, 75, 32, 122, 4};
#+end_src

codice tipo
int[] a = new int[10] {1,2,3,4,5,6,7,8,9,10}

System.out.println(a[5])
Indice sempre positivo, compreso tra 0 e la dimensione dell'array-1

** Lughezza array
per la lughezza array ~nomeArray.length~ uh oh: campo pubblico? protected? coding horror.
Esempio di uso:
#+begin_src java
public int[] getArrayFattorial(final int n)
    {
        int[] fatt = new int[n];
        fatt[0] = 1;
        for (int k=1; k < n; k++) fatt[k] = fatt[k-1] *k;
        return fatt;
    }
#+end_src

** Le dimensioni di un Array non sono modificabili
Una volta dichiarate non crescono dinamicamente, tipo vettore in C++. Bisogna utilizzare il metodo *CopyOf*. Se le dimensioni dell'array sono maggiori di quelle iniziali allora setta al valore di default per il tipo.
#+begin_src java
int[] array = {1,5,8,2,3,4}
    System.out.println(Arrays.toString(array));
array = Arrays.copyOf(array,5); //restringe
System.out.println(Arrays.toString(array));
array = Arrays.copyOf(array,8); //restringe
System.out.println(Arrays.toString(array));
#+end_src

* Array a 2 dimensioni
Possiamo specificare un array a 2 dimensioni semplicemente specificando due coppie di parentesi quadre []:
String[][] matrice = new String[RIGHE][COLONNE]
L'accesso avviene specificando le due dimensioni dell'array:
matrice[y][x].
