#+title: Coseassolutamente da non fare java
#+LATEX_LISTINGS:t
#+LATEX_HEADER: \usepackage{minted}
* Istruzione iterative
troppi corpi, troppi casi.
* Stampare invece di resituire
Stampa solo se è di logging.
* x=x+y
scrivi x+=y
* metodi static che provano a modificare campi d'istanza
Ma il compilatore teoricamente dovrebbe dircelo no.
* Troppe righe di codice
vabbè cerchiamo di essere ragionevoli però non 20 per metodo.
* Oggetti senza dignità
Emh ok... i guess
* Parentesi inutili
diciamo che tengo aperta la slide sulla precedenza.
* Usare float invece di double
comprensibile.
* campi publlici
si spiega da solo

* Costruttore non salva i parametri
qualcosa del tipo:
#+begin_src java
private Punto p1,p2;
public segmento (Punto p1, Punto p2)
   {
       // non fa niente.
   }
#+end_src
* Inizializzazione due volte i campi
solo nel costruttore o se proprio devi quando li dichiari.
* Variabili di appoggio come campi
Non lo devi mai fare.


* Variabili locali a un corpo
tutto dichiarato all'inizio.
